name: Test
on: 
  [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Serve
        run: yarn serve-background
      - name: Check docs links with linkcheck
        uses: filiph/linkcheck@v2.0.15+1
        with:
          arguments: :4200
      - name: Check chain.link with linkcheck
        uses: filiph/linkcheck@v2.0.15+1
        with:
          arguments: https://chain.link
      
